graphics/gimp30: 2.99.2 [build might need retry]
missing dep looks like:
../app/pdb/gimppdb.c:36:10: fatal error: 'core/gimpmarshal.h' file not found

(generated via other deps, hence retry)